version: '3.1'

networks:
  network-zabbix:
    driver: overlay

services:
  mysql:
    image: mariadb:10.3.27
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/neppo/zabbix_stack/db/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Mudar@123 
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Mudar@123
      - LC_ALL=C.UTF-8
      - TZ=America/Sao_Paulo

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.2.2
    networks:
      - network-zabbix
    ports:
      - '10051:10051'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/neppo/zabbix_stack/alertscripts:/usr/lib/zabbix/alertscripts
      - /home/neppo/zabbix_stack/externalscripts:/usr/lib/zabbix/externalscripts
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Mudar@123
      - TZ=America/Sao_Paulo
    depends_on:
      - mysql

  zabbix-frontend:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.2.2
    networks:
      - network-zabbix
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Mudar@123
      - PHP_TZ=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    depends_on:
      - mysql
   
  grafana:
    image: grafana/grafana
    networks:
      - network-zabbix
    ports:
      - '3000:3000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/neppo/zabbix_stack/grafana/:/var/lib/grafana
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - TZ=America/Sao_Paulo
    depends_on:
      - mysql
      - zabbix-server
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-5.2.2
    user: root
    networks:
      - network-zabbix
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
      - TZ=America/Sao_Paulo
    