
version: '3.2'
services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "8080:80"
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=Mudar@!23
      - IPAM_DATABASE_WEBHOST=%
    volumes:
      - /home/neppo/phpipam/phpipam-logo:/var/lib/mysql:/phpipam/css/images/logo
    deploy:
        resources:
            limits:
                cpus: '2'
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=Mudar@123
      - SCAN_INTERVAL=1h
    deploy:
        resources:
            limits:
                cpus: '2'
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Mudar@123
    volumes:
      - /home/neppo/phpipam/phpipamdb:/var/lib/mysql
    deploy:
        resources:
            limits:
                cpus: '2'