print('Seja bem vindo a Pastelaria Devops')
print('Faça seu pedido')
item_pedido = input('Qual sabor do seu Pastel vc deseja: ')
print(f'O pastel pedido foi {item_pedido} - {type(item_pedido)}')
troco = float(input('O Valor do pedido é R$6,00. Qual o valor do troco: '))
print (f' O Tipo do valor do troco é {type(troco)}')