version: '3.2'

services:

    ###########
    # JENKINS #
    ###########    
    jenkins:
        image: jenkins/jenkins
        networks:
            infrasec_jenkins:
                aliases:
                    - jenkins
        ports:
          - '8000:8000'
          - '5000:5000'
        environment:
            JAVA_OPTS: -Duser.timezone=America/Sao_Paulo
            JENKINS_USER: infrasec
            JENKINS_PASS: Mudar@123
        deploy:
            placement:
                constraints: [node.role == manager]
            mode: replicated
            replicas: 1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/opc/infra/jenkins:/var/jenkins_home
networks:
    infrasec_jenkins:
        driver: overlay
